Traceback (most recent call last):
  File "/home/pi/Research/Civil/manager", line 123, in <module>
    day = initialize(mac_storage)
  File "/home/pi/Research/Civil/manager", line 82, in initialize
    day = mac_man.Mac_Man(location)
  File "/home/pi/Research/Civil/mac_man.py", line 14, in __init__
    self.load()
  File "/home/pi/Research/Civil/mac_man.py", line 72, in load
    with open(self.address,'a+') as json_data:
IOError: [Errno 2] No such file or directory: '/home/pi//home/pi/Research/Civil/zoltan.json'
